[var]
SEND_TELEGRAM=1
SEND_SIGNAL=1
SEND_XMPP=1
USER=git
LOG_FILE="/home/git/git_auto_pull.log"
BOT_TOKEN="7120328323:AAFb8_JZvJvrlb5ZFukbxb9SLSW8GkyVITE"
CHAT_ID="899132737"
SIGNAL_SENDER="+380676912725"
SIGNAL_RECIPIENT="+380974894092"
XMPP_RECIPIENT="phone1@openmailserver.net"
XMPP_PASSWORD="gjXLHWy7CzrJzKJpyQxLVH5HcksZjExc"
XMPP_JID="AC_SERVER@openmailserver.net"
XMPP_SERVER="openmailserver.net"
XMPP_PORT="5223"

[projects]
project1_path="/home/git/alteredcarbonllc/ac_store_frontend"
project1_branch="main"
